output "control_plane_ip" {
  value = yandex_compute_instance.control-plane-vm.network_interface.0.nat_ip_address
}

output "worker1_ip" {
  value = yandex_compute_instance.worker1-vm.network_interface.0.nat_ip_address
}

output "worker2_ip" {
  value = yandex_compute_instance.worker2-vm.network_interface.0.nat_ip_address
}

output "container_registry_id" {
  value = yandex_container_registry.netology-registry.id
}

resource "local_file" "tf_nodes_ip" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    tf_master_ip: ${yandex_compute_instance.control-plane-vm.network_interface.0.nat_ip_address}
    tf_worker1_ip: ${yandex_compute_instance.worker1-vm.network_interface.0.nat_ip_address}
    tf_worker2_ip: ${yandex_compute_instance.worker2-vm.network_interface.0.nat_ip_address}
    DOC
  filename = "../tf_nodes_ip.yml"
}
